# List of magazines
#   descr     : description of the magazine
#   filename  : a magazine name starts with 'filename' followed by a number, eg. MagPi01, MagPi123
#   language  : available EN (English), NL (Dutch)
#   directory : the folder which contains the magazines
#   database  : the name of the database

magazines:
  magpi:
    descr: MagPi magazine
    filename: MagPi
    language: EN
    directory: /home/pi/MagSearch/MagPi/
    database: magpi.db
  hackspace:
    descr: HackSpace magazine
    filename: HackSpace
    language: EN
    directory: /home/pi/MagSearch/HackSpace/
    database: hackspace.db

# Default mode of matching search terms to keys. Options are:
#   --any   : any position of the search term in the key word
#   --start : search term has to be at the start of the keyword
#   --exact : exact match between search term and keyword

match_mode: --start

# Maximum allowed gap in page numbers for detecting an article
max_spacing : 2

# Remove words smaller or equal except reserved words (see parser.yml)
remove_size : 2

# GUI settings
textbackgroundcolor: '#FFFFFF'
